### ISSUE TITLE
请教个问题，此demo 是不是 放入KiwiFace.lic 文件就可以查看效果了

### ISSUE THREAD

**Issue by WuGang128** [kiwi-face/KiwiFaceSDK_Demo_Android#2]
如题

**Comment by InLongLAND** [comment]
需要申请KiwiFace.lic，并放在ui中的assets根目录下，就可以执行查看效果了。如果遇到替换后无效的问题，请卸载后重装应用。

**Comment by InLongLAND** [comment]
@a544393709 需要申请KiwiFace.lic，并放在ui中的assets根目录下，把applicationId改成申请时的applicationId，就可以执行查看效果了。如果遇到替换后无效的问题，请卸载后重装应用。
